# .github/workflows/release.yml
---
name: Release XCFramework
on:
  push
  #   tags:
  #     - 'v*.*.*'
jobs:
  release:
    name: Build, publish and release XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install the Apple certificate and provisioning profile
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Checkout dali-framework repo
        uses: actions/checkout@v2
        with:
          repository: kaylenmistry/dali-framework
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: dali-framework
      - name: Create Package.swift file
        run: touch Package.swift
      - name: Build device archive
        working-directory: ./dali-framework
        run: |
          xcodebuild archive \
            -scheme Dali \
            -configuration Release \
            -sdk iphoneos \
            -archivePath 'Dali-iphoneos.xcarchive' \
            SKIP_INSTALL=NO
      - name: Build simulator archive 
        working-directory: ./dali-framework
        run: |
          xcodebuild archive \
            -scheme Dali \
            -configuration Release \
            -sdk iphonesimulator \
            -archivePath 'Dali-iphonesimulator.xcarchive' \
            SKIP_INSTALL=NO
      - name: Create XCFramework
        working-directory: ./dali-framework
        run: |
          xcodebuild -create-xcframework \
            -framework 'Dali-iphoneos.xcarchive/Products/Library/Frameworks/Dali.framework' \
            -framework 'Dali-iphonesimulator.xcarchive/Products/Library/Frameworks/Dali.framework' \
            -output 'Dali.xcframework'
      - name: Compress XCFramework folder
        working-directory: ./dali-framework
        run: zip -r Dali.xcframework.zip Dali.xcframework
      - name: Compute checksum of XCFramework artifact
        working-directory: ./dali-framework
        run: | 
          ARTIFACT_CHECKSUM=`swift package compute-checksum Dali.xcframework.zip`
          echo $ARTIFACT_CHECKSUM > artifact-checksum.txt
      - name: Release XCFramework
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dali-framework/Dali.xcframework.zip
            dali-framework/artifact-checksum.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout dali repo
        uses: actions/checkout@v2
        with:
          repository: kaylenmistry/dali
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: dali
      - name: Setup git config
        run: |
          git config user.name "kaylenmistry"
          git config user.email "kaylenmistry@gmail.com"
      - name: Open Release PR on dali repo
        working-directory: ./dali
        run: |
          RELEASE_VERSION=v0.0.1
          BRANCH_NAME= release/test/$RELEASE_VERSION
          git checkout -b $BRANCH_NAME
          sed -Ei '' 's/(url: "[a-zA-Z0-9.:\/-]+)(v[0-9]+.[0-9]+.[0-9]+)([a-zA-Z0-9.\/-]+")/\1'"$RELEASE_VERSION"'\3/' Package.swift
          sed -Ei '' 's/(checksum: )("[a-f0-9]+")/\1"'"$ARTIFACT_CHECKSUM"'"/' Package.swift
          git add .
          git commit -m "Release $RELEASE_VERSION"
          git push --set-upstream origin $BRANCH_NAME